name: trigger-build
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: trigger
        run: curl -X POST --fail -F token=$DOCKER_BUILD_TOKEN -F ref=main -F "variables[REPOSITORY]=$GITHUB_REPOSITORY" -F "variables[COMMIT_TAG]=$GITHUB_REF_NAME" $DOCKER_BUILD_URL
        env:
          DOCKER_BUILD_TOKEN: ${{ secrets.DOCKER_BUILD_TOKEN }}
          DOCKER_BUILD_URL: ${{ secrets.DOCKER_BUILD_URL }}
